site:
  title: '社内手順書・仕様書'
  description: '社内向け技術文書管理システム'
  baseUrl: '/'

pages:
  - path: 'docs/README.md'
    title: 'README'

  - category: '成果報告会'
    pages:
      - category: 'mm'
        pages:
          - path: 'docs/test/20230414_mm.md'
            title: '2023/04/14'
          - path: 'docs/test/20230421_mm.md'
            title: '2023/04/21'
  - category: '開発関連'
    pages:
      - path: 'docs/setup/environment.md'
        title: '開発環境セットアップ'
      - path: 'docs/setup/deployment.md'
        title: 'デプロイメント手順'
      - path: 'docs/setup.md'
        title: '環境セットアップ手順'
      - category: 'sub'
        pages:
          - path: 'docs/setup/windows.md'
            title: 'Windows環境構築'
          - path: 'docs/setup/macos.md'
            title: 'macOS環境構築'

  - category: 'API'
    pages:
      - path: 'docs/api/authentication.md'
        title: 'API認証仕様'
      - path: 'docs/api/endpoints.md'
        title: 'APIエンドポイント仕様'
      - path: 'docs/api-spec.md'
        title: 'API仕様書'

  - category: 'ガイド'
    pages:
      - path: 'docs/guides/troubleshooting.md'
        title: 'トラブルシューティングガイド'
      - path: 'docs/guides/best-practices.md'
        title: 'ベストプラクティス'
